AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SNSToLambdaToSlack

  - SNS -> Subscription, Lambda -> Slack

Globals:
  Function:
    Timeout: 3
Parameters:
  ServiceName:
    Type: String
    Default: SNSToLambdaToSlack
    Description: Set a clear name for identity

Resources:
  myLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      FunctionName: !Ref ServiceName
      Description: sns->lambda->slack
      MemorySize: 128
      Runtime: python3.8
      Environment:
        Variables:
          hookUrl: ""
          slackChannel: "#general"
      Events:
        MySNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref mySNS
  mySNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Ref ServiceName
      # 透過 AWS::SNS::Topic 建立訂閱, 無法在 CFN 刪除時, 一並刪除
      # Subscription: 
      #   - Endpoint: !GetAtt
      #       - myLambda
      #       - Arn
      #     Protocol: lambda
      TopicName: !Ref ServiceName
  mySNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref 'AWS::AccountId'
          - 'function'
          - !Ref myLambda
      Protocol: lambda
      TopicArn: !Ref mySNS