AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SNSToLambdaToSlack

  - SNS -> Subscription, Lambda -> Slack

Globals:
  Function:
    Timeout: 30
Parameters:
  
  NotifyLambdaName:
    Type: String
    Default: SNSToLambdaToSlack
    Description: Set a clear name for identity
  SlackHookUrl: 
    Type: String
    Default: ""
    Description: "Set slack url, http://..."
  InfoChannel: 
    Type: String
    Default: "#general"
    Description: Set slack url
  IssueChannel: 
    Type: String
    Default: "#general"
    Description: Set slack url

Resources:
  notifyLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      FunctionName: !Ref NotifyLambdaName
      Description: "sns->lambda->slack"
      MemorySize: 128
      Runtime: python3.8
      Environment:
        Variables:
          hookUrl: !Ref SlackHookUrl
          InfoChannel: !Ref InfoChannel
          IssueChannel: !Ref IssueChannel
          InfoTopicArn: !Ref InfoSNS
          IssueTopicArn: !Ref IssueSNS
      Events:
        infoEvent:
          Type: SNS
          Properties:
            Topic: !Ref InfoSNS
        issueEvent:
          Type: SNS
          Properties:
            Topic: !Ref IssueSNS


  ## SNS 
  InfoSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Join 
        - "-"
        - - !Ref NotifyLambdaName
          - "INFO"
      TopicName: !Join 
        - "-"
        - - !Ref NotifyLambdaName
          - "INFO"
  InfoSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref 'AWS::AccountId'
          - 'function'
          - !Ref notifyLambda
      Protocol: lambda
      TopicArn: !Ref InfoSNS
  IssueSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Join 
        - "-"
        - - !Ref NotifyLambdaName
          - "ISSUE"
      # 透過 AWS::SNS::Topic 建立訂閱, 無法在 CFN 刪除時, 一並刪除
      # Subscription: 
      #   - Endpoint: !GetAtt
      #       - myLambda
      #       - Arn
      #     Protocol: lambda
      TopicName: !Join 
        - "-"
        - - !Ref NotifyLambdaName
          - "ISSUE"
  IssueSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref 'AWS::AccountId'
          - 'function'
          - !Ref notifyLambda
      Protocol: lambda
      TopicArn: !Ref IssueSNS